# Changes here will be overwritten by Copier
_commit: ebda788
_src_path: https://github.com/python-project-templates/base.git
add_docs: true
add_extension: js
add_wiki: false
email: dev@1kbgz.com
github: 1kbgz
project_description: Webawesome for spaday
project_name: spaday-webawesome
python_version_primary: '3.11'
team: 1kbgz
